### ISSUE TITLE
game won't launch

### ISSUE THREAD

**Issue by PellucidGames** [a-bakedpotato/Potato-Launcher-Dist#2]
I'm trying to launch 2 games at the same time but it's not launching

**Comment by a-bakedpotato** [comment]
this is caused by battleye and launch provider being server-side, not able to fix this afaik

**Comment by PellucidGames** [comment]
I fixed it, wrong path

**Comment by CapriSun2** [comment]
> Je l'ai corrigé, mauvais chemin

tu a fait comment pour changer
