### ISSUE TITLE
account credential corruption causes infinite loading without opening fortnite

### ISSUE THREAD

**Issue by ArceusMaxis** [a-bakedpotato/Potato-Launcher-Dist#5]
i would like to know what files i should delete for the cache of the authorized code accounts to be reset, as reinstallation did not work.

%localappdata%/potato was deleted in full, but doesn't fix the issue

the particular issue is that, all other accounts work fine and this particular account alone results in an infinite "Launching game on So-and-so id..." message

one possible solution would be to edit the credential file directly in my opinion,
another would be to clear all data present on the computer related to the launcher, but due to my lack of knowledge, im not sure how i would go about doing either

Please kindly help me resolve this issue, thank you for reading

**Comment by a-bakedpotato** [comment]
1. Press Windows + R
2. Insert `%appdata%\a.bakedpotato\fnappv2\tokens`
3. Delete the files inside that folder but not the folder itself.
All common known issues have a pinned solution in my [Discord server](https://discord.gg/9TVJAht)

**Comment by ArceusMaxis** [comment]
THANK YOU <3
